# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dbetaKL_logit <- function(t, beta_t_prior, LP_prior, Z, delta, beta_t, beta_v, K, p, n, eta) {
    .Call(`_DiscreteKL_dbetaKL_logit`, t, beta_t_prior, LP_prior, Z, delta, beta_t, beta_v, K, p, n, eta)
}

NR_boostingKL_logit <- function(t, z, delta, beta_t_prior, LP_prior, beta_t, beta_z, eta, tol, Mstop, step_size) {
    .Call(`_DiscreteKL_NR_boostingKL_logit`, t, z, delta, beta_t_prior, LP_prior, beta_t, beta_z, eta, tol, Mstop, step_size)
}

dbeta_logit <- function(t, Z, delta, beta_t, beta_v, K, p, n) {
    .Call(`_DiscreteKL_dbeta_logit`, t, Z, delta, beta_t, beta_v, K, p, n)
}

boosting_logit <- function(t, z, delta, beta_t, beta_z, tol, Mstop, step_size) {
    .Call(`_DiscreteKL_boosting_logit`, t, z, delta, beta_t, beta_z, tol, Mstop, step_size)
}

Update_logit <- function(t, X, ind, beta_t, beta_v, max_t, c, r) {
    .Call(`_DiscreteKL_Update_logit`, t, X, ind, beta_t, beta_v, max_t, c, r)
}

UpdateKL_logit <- function(t, X, delta, beta_t, beta_v, max_t, c, r, beta_t_tilde, beta_v_tilde, eta) {
    .Call(`_DiscreteKL_UpdateKL_logit`, t, X, delta, beta_t, beta_v, max_t, c, r, beta_t_tilde, beta_v_tilde, eta)
}

NR_logit <- function(t, X, ind, beta_t, beta_v, tol, max_iter) {
    .Call(`_DiscreteKL_NR_logit`, t, X, ind, beta_t, beta_v, tol, max_iter)
}

NRKL_logit <- function(t, X, ind, beta_t, beta_v, tol, max_iter, beta_t_tilde, beta_v_tilde, eta) {
    .Call(`_DiscreteKL_NRKL_logit`, t, X, ind, beta_t, beta_v, tol, max_iter, beta_t_tilde, beta_v_tilde, eta)
}

UpdateKL2_logit <- function(t, X, delta, beta_t, beta_v, max_t, c, r, beta_t_tilde1, beta_v_tilde1, eta1, beta_t_tilde2, beta_v_tilde2, eta2) {
    .Call(`_DiscreteKL_UpdateKL2_logit`, t, X, delta, beta_t, beta_v, max_t, c, r, beta_t_tilde1, beta_v_tilde1, eta1, beta_t_tilde2, beta_v_tilde2, eta2)
}

NRKL2_logit <- function(t, X, ind, beta_t, beta_v, tol, max_iter, beta_t_tilde1, beta_v_tilde1, eta1, beta_t_tilde2, beta_v_tilde2, eta2) {
    .Call(`_DiscreteKL_NRKL2_logit`, t, X, ind, beta_t, beta_v, tol, max_iter, beta_t_tilde1, beta_v_tilde1, eta1, beta_t_tilde2, beta_v_tilde2, eta2)
}

